apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    runtime: native
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongo-volume
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 3Gi
#  hostPath:
#    path: /data/mongo/
#---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
    runtime: native
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        runtime: native
    spec:
      containers:
      - name: mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


