apiVersion: v1
kind: Service
metadata:
  name: temperature-gateway
  labels:
    app: temperature-gateway
    runtime: java
spec:
  type: LoadBalancer
  selector:
    app: temperature-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-gateway
  labels:
    app: temperature-gateway
    runtime: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-gateway
  template:
    metadata:
      labels:
        app: temperature-gateway
        runtime: java
    spec:
      containers:
      - name: temperature-gateway
        image: temperature-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
