apiVersion: v1
kind: Service
metadata:
  name: temperature-service-3
  labels:
    app: temperature-service
    runtime: java
spec:
  type: LoadBalancer
  selector:
    app: temperature-service-3
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-service-3
  labels:
    app: temperature-service-3
    runtime: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-service-3
  template:
    metadata:
      labels:
        app: temperature-service-3
        runtime: java
    spec:
      containers:
      - name: temperature-service-3
        image: temperature-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
